<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StockSymbolsSeeder extends Seeder
{
    public function run()
    {
        $symbols = [
            // Indices
            ['underlying' => 'NIFTY50', 'symbol' => 'NIFTY'],
            ['underlying' => 'BANKNIFTY', 'symbol' => 'BANKNIFTY'],
            
            // A-C
            ['underlying' => 'ABB India Limited', 'symbol' => 'ABB'],
            ['underlying' => 'Aditya Birla Capital Limited', 'symbol' => 'ABCAPITAL'],
            ['underlying' => 'Adani Enterprises Limited', 'symbol' => 'ADANIENT'],
            ['underlying' => 'Adani Ports and Special Economic Zone Limited', 'symbol' => 'ADANIPORTS'],
            ['underlying' => 'Alkem Laboratories Limited', 'symbol' => 'ALKEM'],
            ['underlying' => 'Amber Enterprises India Limited', 'symbol' => 'AMBER'],
            ['underlying' => 'Ambuja Cements Limited', 'symbol' => 'AMBUJACEM'],
            ['underlying' => 'Angel One Limited', 'symbol' => 'ANGELONE'],
            ['underlying' => 'APL Apollo Tubes Limited', 'symbol' => 'APLAPOLLO'],
            ['underlying' => 'Ashok Leyland Limited', 'symbol' => 'ASHOKLEY'],
            ['underlying' => 'Asian Paints Limited', 'symbol' => 'ASIANPAINT'],
            ['underlying' => 'Astral Limited', 'symbol' => 'ASTRAL'],
            ['underlying' => 'Aurobindo Pharma Limited', 'symbol' => 'AUROPHARMA'],
            ['underlying' => 'Axis Bank Limited', 'symbol' => 'AXISBANK'],
            ['underlying' => '360 ONE WAM LIMITED', 'symbol' => '360ONE'],
            ['underlying' => 'Bajaj Auto Limited', 'symbol' => 'BAJAJ-AUTO'],
            ['underlying' => 'Bajaj Finance Limited', 'symbol' => 'BAJFINANCE'],
            ['underlying' => 'Bajaj Finserv Limited', 'symbol' => 'BAJAJFINSV'],
            ['underlying' => 'Bajaj Holdings & Investment Limited', 'symbol' => 'BAJAJHLDNG'],
            ['underlying' => 'Bank of Baroda', 'symbol' => 'BANKBARODA'],
            ['underlying' => 'Bank of India', 'symbol' => 'BANKINDIA'],
            ['underlying' => 'Bharat Dynamics Limited', 'symbol' => 'BDL'],
            ['underlying' => 'Bharat Electronics Limited', 'symbol' => 'BEL'],
            ['underlying' => 'Bharat Forge Limited', 'symbol' => 'BHARATFORG'],
            ['underlying' => 'Bharat Heavy Electricals Limited', 'symbol' => 'BHEL'],
            ['underlying' => 'Bharat Petroleum Corporation Limited', 'symbol' => 'BPCL'],
            ['underlying' => 'Bharti Airtel Limited', 'symbol' => 'BHARTIARTL'],
            ['underlying' => 'Biocon Limited', 'symbol' => 'BIOCON'],
            ['underlying' => 'Blue Star Limited', 'symbol' => 'BLUESTARCO'],
            ['underlying' => 'Bosch Limited', 'symbol' => 'BOSCHLTD'],
            ['underlying' => 'Britannia Industries Limited', 'symbol' => 'BRITANNIA'],
            ['underlying' => 'BSE Limited', 'symbol' => 'BSE'],
            ['underlying' => 'Canara Bank', 'symbol' => 'CANBK'],
            ['underlying' => 'Central Depository Services (India) Limited', 'symbol' => 'CDSL'],
            ['underlying' => 'Cholamandalam Investment and Finance Company Limited', 'symbol' => 'CHOLAFIN'],
            ['underlying' => 'Cipla Limited', 'symbol' => 'CIPLA'],
            ['underlying' => 'Coal India Limited', 'symbol' => 'COALINDIA'],
            ['underlying' => 'Coforge Limited', 'symbol' => 'COFORGE'],
            ['underlying' => 'Colgate Palmolive (India) Limited', 'symbol' => 'COLPAL'],
            ['underlying' => 'Computer Age Management Services Limited', 'symbol' => 'CAMS'],
            ['underlying' => 'Container Corporation of India Limited', 'symbol' => 'CONCOR'],
            ['underlying' => 'Crompton Greaves Consumer Electricals Limited', 'symbol' => 'CROMPTON'],
            ['underlying' => 'Cummins India Limited', 'symbol' => 'CUMMINSIND'],
            
            // D-H
            ['underlying' => 'Dabur India Limited', 'symbol' => 'DABUR'],
            ['underlying' => 'Dalmia Bharat Limited', 'symbol' => 'DALBHARAT'],
            ['underlying' => 'Delhivery Limited', 'symbol' => 'DELHIVERY'],
            ['underlying' => 'Dixon Technologies (India) Limited', 'symbol' => 'DIXON'],
            ['underlying' => 'DLF Limited', 'symbol' => 'DLF'],
            ['underlying' => "Divi's Laboratories Limited", 'symbol' => 'DIVISLAB'],
            ['underlying' => "Dr. Reddy's Laboratories Limited", 'symbol' => 'DRREDDY'],
            ['underlying' => 'Eicher Motors Limited', 'symbol' => 'EICHERMOT'],
            ['underlying' => 'ETERNAL LIMITED', 'symbol' => 'ETERNAL'],
            ['underlying' => 'Exide Industries Limited', 'symbol' => 'EXIDEIND'],
            ['underlying' => 'Fortis Healthcare Limited', 'symbol' => 'FORTIS'],
            ['underlying' => 'GAIL (India) Limited', 'symbol' => 'GAIL'],
            ['underlying' => 'Glenmark Pharmaceuticals Limited', 'symbol' => 'GLENMARK'],
            ['underlying' => 'GMR AIRPORTS LIMITED', 'symbol' => 'GMRAIRPORT'],
            ['underlying' => 'Grasim Industries Limited', 'symbol' => 'GRASIM'],
            ['underlying' => 'Havells India Limited', 'symbol' => 'HAVELLS'],
            ['underlying' => 'HCL Technologies Limited', 'symbol' => 'HCLTECH'],
            ['underlying' => 'HDFC Asset Management Company Limited', 'symbol' => 'HDFCAMC'],
            ['underlying' => 'HDFC Bank Limited', 'symbol' => 'HDFCBANK'],
            ['underlying' => 'HDFC Life Insurance Company Limited', 'symbol' => 'HDFCLIFE'],
            ['underlying' => 'Hero MotoCorp Limited', 'symbol' => 'HEROMOTOCO'],
            ['underlying' => 'Hindalco Industries Limited', 'symbol' => 'HINDALCO'],
            ['underlying' => 'Hindustan Aeronautics Limited', 'symbol' => 'HAL'],
            ['underlying' => 'Hindustan Petroleum Corporation Limited', 'symbol' => 'HINDPETRO'],
            ['underlying' => 'Hindustan Unilever Limited', 'symbol' => 'HINDUNILVR'],
            ['underlying' => 'Hindustan Zinc Limited', 'symbol' => 'HINDZINC'],
            ['underlying' => 'Hitachi Energy India Limited', 'symbol' => 'POWERINDIA'],
            ['underlying' => 'Housing & Urban Development Corporation Limited', 'symbol' => 'HUDCO'],
            
            // I-L
            ['underlying' => 'ICICI Bank Limited', 'symbol' => 'ICICIBANK'],
            ['underlying' => 'ICICI Lombard General Insurance Company Limited', 'symbol' => 'ICICIGI'],
            ['underlying' => 'ICICI Prudential Life Insurance Company Limited', 'symbol' => 'ICICIPRULI'],
            ['underlying' => 'IIFL Finance Limited', 'symbol' => 'IIFL'],
            ['underlying' => 'Indian Bank', 'symbol' => 'INDIANB'],
            ['underlying' => 'Indian Energy Exchange Limited', 'symbol' => 'IEX'],
            ['underlying' => 'Indian Hotels Company Limited', 'symbol' => 'INDHOTEL'],
            ['underlying' => 'Indian Oil Corporation Limited', 'symbol' => 'IOC'],
            ['underlying' => 'Indian Railway Catering And Tourism Corporation Limited', 'symbol' => 'IRCTC'],
            ['underlying' => 'Indian Railway Finance Corporation Limited', 'symbol' => 'IRFC'],
            ['underlying' => 'Indian Renewable Energy Development Agency Limited', 'symbol' => 'IREDA'],
            ['underlying' => 'IndusInd Bank Limited', 'symbol' => 'INDUSINDBK'],
            ['underlying' => 'Indus Towers Limited', 'symbol' => 'INDUSTOWER'],
            ['underlying' => 'Info Edge (India) Limited', 'symbol' => 'NAUKRI'],
            ['underlying' => 'Infosys Limited', 'symbol' => 'INFY'],
            ['underlying' => 'Inox Wind Limited', 'symbol' => 'INOXWIND'],
            ['underlying' => 'InterGlobe Aviation Limited', 'symbol' => 'INDIGO'],
            ['underlying' => 'JINDAL STEEL LIMITED', 'symbol' => 'JINDALSTEL'],
            ['underlying' => 'Jio Financial Services Limited', 'symbol' => 'JIOFIN'],
            ['underlying' => 'JSW Energy Limited', 'symbol' => 'JSWENERGY'],
            ['underlying' => 'JSW Steel Limited', 'symbol' => 'JSWSTEEL'],
            ['underlying' => 'Jubilant Foodworks Limited', 'symbol' => 'JUBLFOOD'],
            ['underlying' => 'Kalyan Jewellers India Limited', 'symbol' => 'KALYANKJIL'],
            ['underlying' => 'Kaynes Technology India Limited', 'symbol' => 'KAYNES'],
            ['underlying' => 'KEI Industries Limited', 'symbol' => 'KEI'],
            ['underlying' => 'Kfin Technologies Limited', 'symbol' => 'KFINTECH'],
            ['underlying' => 'Kotak Mahindra Bank Limited', 'symbol' => 'KOTAKBANK'],
            ['underlying' => 'KPIT Technologies Limited', 'symbol' => 'KPITTECH'],
            ['underlying' => 'L&T Finance Limited', 'symbol' => 'LTF'],
            ['underlying' => 'Larsen & Toubro Limited', 'symbol' => 'LT'],
            ['underlying' => 'Laurus Labs Limited', 'symbol' => 'LAURUSLABS'],
            ['underlying' => 'LIC Housing Finance Limited', 'symbol' => 'LICHSGFIN'],
            ['underlying' => 'Life Insurance Corporation Of India', 'symbol' => 'LICI'],
            ['underlying' => 'LTIMindtree Limited', 'symbol' => 'LTIM'],
            ['underlying' => 'Lodha Developers Limited', 'symbol' => 'LODHA'],
            ['underlying' => 'Lupin Limited', 'symbol' => 'LUPIN'],
            
            // M-P
            ['underlying' => 'Mahindra & Mahindra Limited', 'symbol' => 'M&M'],
            ['underlying' => 'Manappuram Finance Limited', 'symbol' => 'MANAPPURAM'],
            ['underlying' => 'Mankind Pharma Limited', 'symbol' => 'MANKIND'],
            ['underlying' => 'Marico Limited', 'symbol' => 'MARICO'],
            ['underlying' => 'Maruti Suzuki India Limited', 'symbol' => 'MARUTI'],
            ['underlying' => 'Max Financial Services Limited', 'symbol' => 'MFSL'],
            ['underlying' => 'Max Healthcare Institute Limited', 'symbol' => 'MAXHEALTH'],
            ['underlying' => 'Mazagon Dock Shipbuilders Limited', 'symbol' => 'MAZDOCK'],
            ['underlying' => 'MphasiS Limited', 'symbol' => 'MPHASIS'],
            ['underlying' => 'Multi Commodity Exchange of India Limited', 'symbol' => 'MCX'],
            ['underlying' => 'Muthoot Finance Limited', 'symbol' => 'MUTHOOTFIN'],
            ['underlying' => 'NBCC (India) Limited', 'symbol' => 'NBCC'],
            ['underlying' => 'Nestle India Limited', 'symbol' => 'NESTLEIND'],
            ['underlying' => 'NHPC Limited', 'symbol' => 'NHPC'],
            ['underlying' => 'NMDC Limited', 'symbol' => 'NMDC'],
            ['underlying' => 'NTPC Limited', 'symbol' => 'NTPC'],
            ['underlying' => 'National Aluminium Company Limited', 'symbol' => 'NATIONALUM'],
            ['underlying' => 'Nuvama Wealth Management Limited', 'symbol' => 'NUVAMA'],
            ['underlying' => 'Oberoi Realty Limited', 'symbol' => 'OBEROIRLTY'],
            ['underlying' => 'Oil & Natural Gas Corporation Limited', 'symbol' => 'ONGC'],
            ['underlying' => 'Oil India Limited', 'symbol' => 'OIL'],
            ['underlying' => 'One 97 Communications Limited', 'symbol' => 'PAYTM'],
            ['underlying' => 'Oracle Financial Services Software Limited', 'symbol' => 'OFSS'],
            ['underlying' => 'PB Fintech Limited', 'symbol' => 'POLICYBZR'],
            ['underlying' => 'PG Electroplast Limited', 'symbol' => 'PGEL'],
            ['underlying' => 'PI Industries Limited', 'symbol' => 'PIIND'],
            ['underlying' => 'PNB Housing Finance Limited', 'symbol' => 'PNBHOUSING'],
            ['underlying' => 'Page Industries Limited', 'symbol' => 'PAGEIND'],
            ['underlying' => 'Patanjali Foods Limited', 'symbol' => 'PATANJALI'],
            ['underlying' => 'Persistent Systems Limited', 'symbol' => 'PERSISTENT'],
            ['underlying' => 'Petronet LNG Limited', 'symbol' => 'PETRONET'],
            ['underlying' => 'Pidilite Industries Limited', 'symbol' => 'PIDILITIND'],
            ['underlying' => 'Piramal Pharma Limited', 'symbol' => 'PPLPHARMA'],
            ['underlying' => 'Polycab India Limited', 'symbol' => 'POLYCAB'],
            ['underlying' => 'Power Finance Corporation Limited', 'symbol' => 'PFC'],
            ['underlying' => 'Power Grid Corporation of India Limited', 'symbol' => 'POWERGRID'],
            ['underlying' => 'Premier Energies Limited', 'symbol' => 'PREMIERENE'],
            ['underlying' => 'Prestige Estates Projects Limited', 'symbol' => 'PRESTIGE'],
            ['underlying' => 'Punjab National Bank', 'symbol' => 'PNB'],
            
            // R-Z
            ['underlying' => 'RBL Bank Limited', 'symbol' => 'RBLBANK'],
            ['underlying' => 'REC Limited', 'symbol' => 'RECLTD'],
            ['underlying' => 'Rail Vikas Nigam Limited', 'symbol' => 'RVNL'],
            ['underlying' => 'Reliance Industries Limited', 'symbol' => 'RELIANCE'],
            ['underlying' => 'SBI Cards and Payment Services Limited', 'symbol' => 'SBICARD'],
            ['underlying' => 'SBI Life Insurance Company Limited', 'symbol' => 'SBILIFE'],
            ['underlying' => 'SRF Limited', 'symbol' => 'SRF'],
            ['underlying' => 'Sammaan Capital Limited', 'symbol' => 'SAMMAANCAP'],
            ['underlying' => 'Samvardhana Motherson International Limited', 'symbol' => 'MOTHERSON'],
            ['underlying' => 'Shriram Finance Limited', 'symbol' => 'SHRIRAMFIN'],
            ['underlying' => 'Siemens Limited', 'symbol' => 'SIEMENS'],
            ['underlying' => 'Solar Industries India Limited', 'symbol' => 'SOLARINDS'],
            ['underlying' => 'Sona BLW Precision Forgings Limited', 'symbol' => 'SONACOMS'],
            ['underlying' => 'State Bank of India', 'symbol' => 'SBIN'],
            ['underlying' => 'Steel Authority of India Limited', 'symbol' => 'SAIL'],
            ['underlying' => 'Sun Pharmaceutical Industries Limited', 'symbol' => 'SUNPHARMA'],
            ['underlying' => 'Supreme Industries Limited', 'symbol' => 'SUPREMEIND'],
            ['underlying' => 'Suzlon Energy Limited', 'symbol' => 'SUZLON'],
            ['underlying' => 'Swiggy Limited', 'symbol' => 'SWIGGY'],
            ['underlying' => 'Syngene International Limited', 'symbol' => 'SYNGENE'],
            ['underlying' => 'TATA CONSUMER PRODUCTS LIMITED', 'symbol' => 'TATACONSUM'],
            ['underlying' => 'TVS Motor Company Limited', 'symbol' => 'TVSMOTOR'],
            ['underlying' => 'Tata Consultancy Services Limited', 'symbol' => 'TCS'],
            ['underlying' => 'Tata Elxsi Limited', 'symbol' => 'TATAELXSI'],
            ['underlying' => 'Tata Motors Passenger Vehicles Limited', 'symbol' => 'TMPV'],
            ['underlying' => 'Tata Power Company Limited', 'symbol' => 'TATAPOWER'],
            ['underlying' => 'Tata Steel Limited', 'symbol' => 'TATASTEEL'],
            ['underlying' => 'Tata Technologies Limited', 'symbol' => 'TATATECH'],
            ['underlying' => 'Tech Mahindra Limited', 'symbol' => 'TECHM'],
            ['underlying' => 'The Federal Bank Limited', 'symbol' => 'FEDERALBNK'],
            ['underlying' => 'The Phoenix Mills Limited', 'symbol' => 'PHOENIXLTD'],
            ['underlying' => 'Titan Company Limited', 'symbol' => 'TITAN'],
            ['underlying' => 'Torrent Pharmaceuticals Limited', 'symbol' => 'TORNTPHARM'],
            ['underlying' => 'Torrent Power Limited', 'symbol' => 'TORNTPOWER'],
            ['underlying' => 'Trent Limited', 'symbol' => 'TRENT'],
            ['underlying' => 'Tube Investments of India Limited', 'symbol' => 'TIINDIA'],
            ['underlying' => 'UNO Minda Limited', 'symbol' => 'UNOMINDA'],
            ['underlying' => 'UPL Limited', 'symbol' => 'UPL'],
            ['underlying' => 'UltraTech Cement Limited', 'symbol' => 'ULTRACEMCO'],
            ['underlying' => 'Union Bank of India', 'symbol' => 'UNIONBANK'],
            ['underlying' => 'United Spirits Limited', 'symbol' => 'UNITDSPR'],
            ['underlying' => 'Varun Beverages Limited', 'symbol' => 'VBL'],
            ['underlying' => 'Vedanta Limited', 'symbol' => 'VEDL'],
            ['underlying' => 'Voltas Limited', 'symbol' => 'VOLTAS'],
            ['underlying' => 'Waaree Energies Limited', 'symbol' => 'WAAREEENER'],
            ['underlying' => 'Zydus Lifesciences Limited', 'symbol' => 'ZYDUSLIFE'],
        ];

        // Create a temporary table to store available symbols
        // DB::statement('CREATE TEMPORARY TABLE IF NOT EXISTS temp_stock_symbols (
        //     underlying VARCHAR(255),
        //     symbol VARCHAR(50)
        // )');

        // Insert all symbols
        // foreach (array_chunk($symbols, 100) as $chunk) {
        //     DB::table('temp_stock_symbols')->insert($chunk);
        // }

        foreach (array_chunk($symbols, 100) as $chunk) {
            DB::table('symbol_lists')->insert($chunk);
        }

        $this->command->info('Stock symbols seeder completed! Total symbols: ' . count($symbols));
        $this->command->info('Symbols are stored in temporary table "temp_stock_symbols"');
        $this->command->info('Use these symbols when assigning to brokers');
    }
}