@extends($activeTemplate . 'layouts.master')

@section('content')
@push('style')
<style>
    .page-header { background:linear-gradient(135deg,#11998e,#38ef7d); color:white; padding:20px 26px; border-radius:14px; margin-bottom:22px; box-shadow:0 6px 20px rgba(17,153,142,0.4); }
    .page-header h4 { font-size:1.3rem; margin:0 0 4px; font-weight:700; }
    .page-header p  { font-size:12px; margin:0; opacity:.85; }

    .config-card { background:#fff; border-radius:12px; padding:16px 20px; margin-bottom:20px; box-shadow:0 3px 12px rgba(0,0,0,.08); }
    .config-item { display:inline-block; margin-right:20px; margin-bottom:6px; font-size:12px; }
    .config-item span { font-weight:700; color:#11998e; }

    .custom--table thead th { background:#f8f9fa; font-size:11px; font-weight:700; text-transform:uppercase; letter-spacing:.5px; vertical-align:middle; padding:10px !important; }
    .custom--table tbody td { font-size:12px; vertical-align:middle; padding:10px !important; }

    .badge-open-high { background:#fde8e8; color:#c82333; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }
    .badge-open-low  { background:#e8f8e8; color:#155724; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }
    .badge-placed    { background:#d4edda; color:#155724; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }
    .badge-pending   { background:#fff3cd; color:#856404; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }
    .badge-ce        { background:#d4edda; color:#155724; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }
    .badge-pe        { background:#fde8e8; color:#c82333; font-size:10px; padding:3px 9px; border-radius:10px; font-weight:700; }

    .stats-box { background:#fff; padding:14px; border-radius:10px; text-align:center; border-left:4px solid #11998e; box-shadow:0 2px 8px rgba(0,0,0,.07); margin-bottom:18px; }
    .stats-box small  { display:block; color:#888; font-size:10px; text-transform:uppercase; }
    .stats-box strong { display:block; font-size:1.5rem; font-weight:700; margin-top:2px; }
    label { color:#000 !important; }
</style>
@endpush

<section class="pt-50 pb-50">
<div class="container-fluid content-container">

    {{-- Header --}}
    <div class="page-header">
        <div class="d-flex justify-content-between align-items-center">
            <div>
                <h4>{{ $pageTitle }}</h4>
                <p>All orders generated by this configuration</p>
            </div>
            <a href="{{ route('fut-ohl-auto.config') }}" class="btn btn-light btn-sm">
                <i class="fas fa-arrow-left"></i> Back to Configs
            </a>
        </div>
    </div>

    {{-- Config summary card --}}
    <div class="config-card">
        <h6 style="color:#11998e; font-weight:700; margin-bottom:10px;">Config #{{ $config->id }} Details</h6>
        <div>
            <div class="config-item">Broker: <span>{{ $config->broker->client_name ?? 'N/A' }}</span></div>
            <div class="config-item">Tolerance: <span>±{{ $config->tolerance }} pts</span></div>
            <div class="config-item">Mode: <span>{{ strtoupper($config->signal_mode) }}</span></div>
            <div class="config-item">Order: <span>{{ $config->order_type }}</span></div>
            <div class="config-item">Product: <span>{{ $config->product }}</span></div>
            <div class="config-item">Series: <span>{{ strtoupper($config->option_series) }}</span></div>
            <div class="config-item">CE Lots: <span>{{ $config->ce_quantity }}</span></div>
            <div class="config-item">PE Lots: <span>{{ $config->pe_quantity }}</span></div>
            <div class="config-item">
                Status:
                @if($config->status)
                    <span style="color:#28a745;">✅ Active</span>
                @else
                    <span style="color:#dc3545;">❌ Inactive</span>
                @endif
            </div>
        </div>
    </div>

    {{-- Stats --}}
    <div class="row mb-2">
        <div class="col-6 col-md-3">
            <div class="stats-box"><small>Total Orders</small><strong class="text-dark">{{ $orders->total() }}</strong></div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stats-box" style="border-left-color:#28a745;">
                <small>Placed</small><strong style="color:#28a745;">{{ $orders->where('is_order_placed', true)->count() }}</strong>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stats-box" style="border-left-color:#ffc107;">
                <small>Pending</small><strong style="color:#ffc107;">{{ $orders->where('is_order_placed', false)->count() }}</strong>
            </div>
        </div>
        <div class="col-6 col-md-3">
            <div class="stats-box" style="border-left-color:#dc3545;">
                <small>Open=High (PE)</small><strong style="color:#dc3545;">{{ $orders->where('signal_type', 'OPEN=HIGH')->count() }}</strong>
            </div>
        </div>
    </div>

    {{-- Orders table --}}
    <div class="table-responsive">
        <table class="table custom--table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Date</th>
                    <th>Symbol</th>
                    <th>Signal</th>
                    <th>9:15 Open</th>
                    <th>9:15 High</th>
                    <th>9:15 Low</th>
                    <th>Type</th>
                    <th>Option</th>
                    <th>Strike</th>
                    <th>Entry ₹</th>
                    <th>Qty</th>
                    <th>Series</th>
                    <th>Tol</th>
                    <th>Placed</th>
                </tr>
            </thead>
            <tbody>
                @forelse($orders as $i => $order)
                <tr>
                    <td><strong>{{ $orders->firstItem() + $i }}</strong></td>
                    <td><span style="font-size:11px;">{{ $order->signal_date }}</span></td>
                    <td><strong style="color:#11998e; font-size:13px;">{{ $order->symbol }}</strong></td>
                    <td>
                        <span class="{{ $order->signal_type === 'OPEN=HIGH' ? 'badge-open-high' : 'badge-open-low' }}">
                            {{ $order->signal_type ?? '—' }}
                        </span>
                    </td>
                    <td>₹{{ number_format($order->open_price, 2) }}</td>
                    <td>
                        @if($order->signal_type === 'OPEN=HIGH')
                            <span style="color:#dc3545; font-weight:700;">₹{{ number_format($order->high_915, 2) }}</span>
                        @else
                            {{ '₹' . number_format($order->high_915, 2) }}
                        @endif
                    </td>
                    <td>
                        @if($order->signal_type === 'OPEN=LOW')
                            <span style="color:#28a745; font-weight:700;">₹{{ number_format($order->low_915, 2) }}</span>
                        @else
                            {{ '₹' . number_format($order->low_915, 2) }}
                        @endif
                    </td>
                    <td>
                        <span class="{{ $order->option_type === 'CE' ? 'badge-ce' : 'badge-pe' }}">
                            {{ $order->option_type ?? '—' }}
                        </span>
                    </td>
                    <td><small>{{ $order->option_symbol ?? '—' }}</small></td>
                    <td>{{ $order->strike_price ? '₹' . number_format($order->strike_price, 2) : '—' }}</td>
                    <td><strong>₹{{ number_format($order->entry_price, 2) }}</strong></td>
                    <td><strong style="color:#11998e;">{{ $order->quantity }}</strong></td>
                    <td><small class="text-muted">{{ $order->series_expiry ?? '—' }}</small></td>
                    <td><small>±{{ $order->tolerance_used }}pt</small></td>
                    <td>
                        @if($order->is_order_placed)
                            <span class="badge-placed">✅ Placed</span>
                            @if($order->order_placed_at)
                                <br><small class="text-muted">{{ $order->order_placed_at->format('H:i:s') }}</small>
                            @endif
                        @else
                            <span class="badge-pending">⏳ Pending</span>
                            @if($order->failure_reason)
                                <br><small class="text-danger" title="{{ $order->failure_reason }}">⚠ Failed</small>
                            @endif
                        @endif
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="15" class="text-center py-5">
                        <i class="fas fa-inbox" style="font-size:2rem; opacity:.3; color:#11998e;"></i>
                        <p class="mt-2 text-muted">No orders yet for this configuration.</p>
                    </td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    @if($orders->hasPages())
    <div class="p-3">{{ $orders->links() }}</div>
    @endif

</div>
</section>
@endsection